FROM node:12-slim@sha256:c28ca4124ac84ff1e72ee68abfe70aa4cc86f499c1ef20408dc2d35af1058ac1

WORKDIR /app

COPY internal/test/integration/components/nodemultiproc/service_node12.js service.js
COPY internal/test/integration/components/nodemultiproc/start-all.js .

EXPOSE 5000 5001 5002 5003

CMD [ "node", "start-all.js" ]
